# Generated by Django 4.2 on 2023-04-06 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mfaofficers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('officenumber', models.IntegerField()),
                ('natureofproblem', models.CharField(choices=[('internet', 'internet'), ('computer_issue', 'computer_issue'), ('request meeting', 'request meeting'), ('other', 'other')], default='internet', max_length=20)),
                ('directorate', models.TextField(max_length=50)),
                ('division', models.TextField(max_length=50)),
                ('station', models.TextField(max_length=50)),
                ('name', models.CharField(max_length=30)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mfaofficers.mfaofficeruser')),
            ],
        ),
    ]
