# Generated by Django 4.2 on 2023-04-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_tasks_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='taskdescription',
            field=models.TextField(default='Describe here nature of prooblem', max_length=200),
        ),
    ]
