# Generated by Django 4.2 on 2023-04-06 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_taskdescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='taskdescription',
            field=models.TextField(default='Describe here nature of problem', max_length=200),
        ),
    ]
